# Project
version=2.0.1
java_version=25

# Minecraft & Platforms
minecraft_version=26.1.2
paper_api_version=26.1.2.build.+
loader_version=0.19.3
fabric_api_version=0.155.0+26.1.2

# Gradle Plugins
loom_version=1.17-SNAPSHOT
shadow_version=9.4.1
run_paper_version=3.1.0

# VoiceChat & Audio
voicechat_api_version=2.6.20
voicechat_modrinth_version=fabric-2.6.24+26.1.2
vosk_version=0.3.45
jna_version=5.14.0
mp3spi_version=1.9.5-1
jlayer_version=1.0.1-1
tritonus_version=0.3.7-1

# Libraries & Tools
annotations_version=26.0.2
lombok_version=1.18.44
jackson_version=2.19.1
snakeyaml_version=2.2

# Commands & Frameworks
cloud_legacy_version=1.8.4
cloud_core_version=2.0.0
cloud_fabric_version=2.0.0-beta.16
dream_api_version=0.5.3
luckperms_version=5.4
devlogin_version=3.5.1
