plugins {
  id 'xyz.jpenilla.run-paper' version '3.1.0'
}

repositories {
  mavenCentral()
}

dependencies {
  api project(":api")
}

base {
  archivesName.set("dreamvoice-core")
}

tasks {
  shadowJar {
    archiveFileName = "DreamVoice.jar"
    manifest {
      attributes["Main-Class"] = "fr.dreamin.dreamvoice.core.DreamVoice"
    }
  }

  runServer {
    minecraftVersion("26.1.2")
  }
}

processResources {
  def props = [
    'version': version,
    'description': description,
    'apiVersion': '26.1'
  ]
  inputs.properties(props)
  filteringCharset 'UTF-8'
  filesMatching('paper-plugin.yml') {
    expand(props)
  }
}